[package]
name = "euc"
version = "0.2.0"
description = "A software rendering crate that lets you write shaders with Rust"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
license = "Apache-2.0 AND MIT"
repository = "https://github.com/zesterer/euc"
readme = "README.md"
edition = "2018"
keywords = ["renderer", "3D", "graphics", "raster"]
exclude = [
	"/misc",
	"/misc/*",
]

[dependencies]
vek = "0.9"

[dev-dependencies]
minifb = "0.11"
tobj = "0.1"
criterion = "0.2"

[lib]
bench = false

[[bench]]
name = "teapot"
harness = false

[features]
nightly = []

[profile.dev]
# Optimize by default so we don't need to remember to always pass in --release
opt-level = 3
